-- +goose Up
CREATE TABLE feed_follows(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 feed_id UUID REFERENCES feeds(id) ON DELETE CASCADE
 user_id UUID REFERENCES users(id) ON DELETE CASCADE
);

-- +goose Down
DROP TABLE feed_follows;